### ISSUE TITLE
Still Image Trigger Control with VS_STILL_IMAGE_TRIGGER_CONTROL

### ISSUE THREAD

**Issue by kevin-zqw** [mrRay/VVUVCKit#6]
Hi, thanks so much for your library.
Do you know how to take still image with VS_STILL_IMAGE_TRIGGER_CONTROL? aka how to send this command, and how to get the image data back from uvc camera?

**Comment by oliverschaefer** [comment]
@kevin-zqw Have you found an example of how to do this, yet?

**Comment by kevin-zqw** [comment]
@oliverschaefer Nope, it seems like there is no way to do this feature.
